### ISSUE TITLE
Toggle on index screen

### ISSUE THREAD

**Issue by ecano08** [davidpiesse/nova-toggle#15]
Hi! It's a great feature but I have a doubt, I try to add a toggle field in the index but only display a dot with red or green color, I'm not sure if I am missing something or why It's not working, can somebody explain me? Thanks

**Comment by davidpiesse** [comment]
Hi @ecano08 ,

That is the current functionality. The index screen does not include a toggle - but just a true/false indicator (the dot).

If you want you can PR any new functionality and I'll add it in :) 

D

**Comment by bernhardh** [comment]
Maybe I missunderstand something, but this is already implemented in master (`editableIndex`), right? Its just not documented, nor it is included into the released versions.

Could you please release this functionality? Would be great! Would also solve #11

**Comment by davidpiesse** [comment]
You are right @bernhardh !
It's not yet documented - but it should be useable and in a pre-release version (0.0.7).
Could you check you see it if you upgrade to this version?

If so I will ensure that this goes to full release asap.

**Comment by bernhardh** [comment]
See updated comment. I saw it now, that its in 0.0.7, but this isn't available over composer (github autosync disabled/broken)?

**Comment by bernhardh** [comment]
Using `dev-master` now. And it works. Documentation would be great for other users.

**Comment by bernhardh** [comment]
Sorry to spam these comments. It doesn't work. I can see the toggle and click it, but it doesn't send a request, so it does nothing.

**Comment by davidpiesse** [comment]
No worries.
The same code is used in both the form field and the index field - but obviously they do not work the same.
What I think should happen is the Index field would have to send off a request to update that specific model & field via an ajax request.
So right now this hasn't been implemented and would need to be added.
TODO: Add API call using axios to update the resource with the new value for the field.

PR very welcome to add this in! :)
