### ISSUE TITLE
The Toggle does not opening in the Detail Page

### ISSUE THREAD

**Issue by ltd300** [davidpiesse/nova-toggle#22]
Hi David,
Thank you so much for this package.
 In the create and update page is working great but my issue is that the detail page(view page) is not showing the data even if I save the toggle open.

**Comment by davidpiesse** [comment]
Have you got a screenshot and a copy of your Nova code for the field?

**Comment by ltd300** [comment]
Thank for your time!!


   Toggle::make('Hide/Show Panel', 'panel_4')
              ->trueValue('On')
              ->falseValue('Off')
              ->hideFromIndex(),
![Screen Shot 2020-03-26 at 6 18 36 PM](https://user-images.githubusercontent.com/6537367/77702185-54627800-6f8e-11ea-9a3a-c1713adc9ad7.png)


   NovaDependencyContainer::make([

           Checkboxes::make('Consent for Treatment', 'consent')->options([

           'I Authorize' => 'I, Authorize the staff 
![Screen Shot 2020-03-26 at 6 18 36 PM](https://user-images.githubusercontent.com/6537367/77702264-7eb43580-6f8e-11ea-9a21-aa472c2df86b.png)
 to provide services.',

            'I Realease'  => 'Authorize release of necessary information from my service record to any insurer, compensation carrier, or other agency providing financial assistance for treatment/ services Information from clinical records may be used by The Department of Children and Families, and/or Human Rights Advocacy Committee for the purpose of monitoring facility, activity and complaints concerning the facility.',

            ])->saveAsString()->saveUncheckedValues()->hideFromIndex()

])->dependsOn('panel_4', 1),

**Comment by ltd300** [comment]
Thank you for your time!!

    Toggle::make('Hide/Show Panel', 'panel_4')
              ->trueValue('On')
              ->falseValue('Off')
              ->hideFromIndex(),

   NovaDependencyContainer::make([

           Checkboxes::make('Consent for Treatment', 'consent')->options([

           'I Authorize' => 'I, Authorize the staff of Lighthouse Community Center, LLC to provide services.',

            'I Realease'  => 'Authorize release of necessary information from my service record to any insurer, compensation carrier, or other agency providing financial assistance for treatment/ services Information from clinical records may be used by The Department of Children and Families, and/or Human Rights Advocacy Committee for the purpose of monitoring facility, activity and complaints concerning the facility.',

            ])->saveAsString()->saveUncheckedValues()->hideFromIndex()

])->dependsOn('panel_4', 1),



![Screen Shot 2020-03-26 at 6 18 36 PM](https://user-images.githubusercontent.com/6537367/77702357-b327f180-6f8e-11ea-9305-1f7c805dc254.png)

**Comment by davidpiesse** [comment]
Are you looking to toggle panels with this tool?
If so - alas it can't do that. It only shows its 'editing state' on the create and edit pages.

**Comment by ltd300** [comment]
Yes that is exactly what I was trying to do. I'm toggling the panel because I have a very large form.
Thank you so much for your help and quick response.

**Comment by davidpiesse** [comment]
No worries

This might be useful to easily show hide things in a different way.

https://novapackages.com/packages/eminiarts/nova-tabs

Regards,
David

**Comment by ltd300** [comment]
Thank you!!
