### ISSUE TITLE
Labels not showing in details screen

### ISSUE THREAD

**Issue by elrufoelrufo** [davidpiesse/nova-toggle#3]
Hello,
First of all thank for your package for nova. Is there any way to show labels in details screen ? Now only it showing true or false.
Thanks!!

**Comment by davidpiesse** [comment]
Hi!
Have you got your field code? Could you paste it in here?

For custom labels it should be:
```php
Toggle::make('Active')
    ->trueLabel('Tru Dat')
    ->falseLabel('Nah Dawg')
```

**Comment by davidpiesse** [comment]
If you want to show the labels you need to enable them also. It is not clear in the documentation. I will fix that.

This means something like
```php
Toggle::make('toggle')
->showLabels()
->trueLabel('Yay')
->falseLabel('Nah')
```

There is also
```php
->showOnlyTrueLabel()
```
and
```php
->showOnlyFalseLabel()
```

**Comment by davidpiesse** [comment]
I'll have a look into this it may be fixed in a release from last week :).

D

**Comment by elrufoelrufo** [comment]
Yeah, I have updated to version 0.0.5 and it's working properly. D

Thank you.
