### ISSUE TITLE
Use localization in detail view

### ISSUE THREAD

**Issue by daguilarm** [davidpiesse/nova-toggle#4]
Will be nice to use the trueLabel() and falseLabel() methods in the detail view, because right now you can see this:

<img width="174" alt="captura de pantalla 2018-09-30 a las 22 25 15" src="https://user-images.githubusercontent.com/2663941/46262318-f0c5ce80-c4ff-11e8-952d-814b5d1ee853.png">

So if I use something like this: falseLabel('Falso'), I will see "falso" instead of "false".

**Comment by davidpiesse** [comment]
I am adding this to Index and Detail View :)
